all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:
    web:
      hosts:
        web1:
          ansible_host: 192.168.1.10

    db:
      hosts:
        db1:
          ansible_host: 192.168.1.11
